In [3]:
pwd
# cd ..

NameError: name 'pwd' is not defined

In [2]:
import pandas as pd

In [5]:
# log_df = pd.read_csv("data/interim/mdl_logstore_standard_log_100000.csv")
# badge_df = pd.read_csv("data/raw/mdl_badge_issued.csv")
# course_modules_df = pd.read_csv("data/raw/mdl_course_modules.csv")
# completion_df = pd.read_csv("data/raw/mdl_course_modules_completion.csv")
# grades_history_df = pd.read_csv("data/raw/mdl_grade_grades_history.csv")
# user_df = pd.read_csv("data/raw/mdl_user.csv")

### Users

In [4]:
user_df = pd.read_csv("data/raw/mdl_user.csv")

IOError: File data/raw/mdl_user.csv does not exist

In [6]:
user_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2170 entries, 0 to 2169
Data columns (total 48 columns):
id                   2170 non-null int64
confirmed            2170 non-null int64
deleted              2170 non-null int64
suspended            2170 non-null int64
mnethostid           2170 non-null int64
username             2170 non-null object
idnumber             0 non-null float64
firstname            2170 non-null object
lastname             2170 non-null object
email                2170 non-null object
emailstop            2170 non-null int64
icq                  1 non-null object
skype                26 non-null object
yahoo                5 non-null object
aim                  0 non-null float64
msn                  2 non-null object
phone1               19 non-null object
phone2               23 non-null object
institution          49 non-null object
department           36 non-null object
address              21 non-null object
city                 1861 non-null object
country              2063 non-null object
lang                 2170 non-null object
theme                4 non-null object
timezone             2170 non-null object
firstaccess          2170 non-null int64
lastaccess           2170 non-null int64
lastlogin            2170 non-null int64
currentlogin         2170 non-null int64
lastip               2170 non-null object
picture              2170 non-null int64
url                  74 non-null object
description          243 non-null object
descriptionformat    2170 non-null int64
mailformat           2170 non-null int64
maildigest           2170 non-null int64
maildisplay          2170 non-null int64
autosubscribe        2170 non-null int64
trackforums          2170 non-null int64
timecreated          2170 non-null int64
timemodified         2170 non-null int64
trustbitmask         2170 non-null int64
lastnamephonetic     21 non-null object
firstnamephonetic    27 non-null object
middlename           8 non-null object
alternatename        12 non-null object
calendartype         2170 non-null object
dtypes: float64(2), int64(20), object(26)
memory usage: 813.8+ KB

In [7]:
user_df.head()

,id,confirmed,deleted,suspended,mnethostid,username,idnumber,firstname,lastname,email,...,autosubscribe,trackforums,timecreated,timemodified,trustbitmask,lastnamephonetic,firstnamephonetic,middlename,alternatename,calendartype
0,0,1,0,0,1,user186977097674129409,NaN,WjLE Pjb a VUQhOz yem tGdQmvn,r nrmZZflGFBbefW REfdbNtc,lhIh LplRfJO kFOnSFr vgzdkgCX,...,1,1,1458663475,1487132351,0,NaN,NaN,NaN,NaN,gregorian
1,0,1,0,0,1,user4786049973974204417,NaN,gDOm SYE kqhByCiKt UKeBhg dhsS,rYPW nh uwBnv mRBNDSqXARSS,NVLCcu ynMuo F JTxPtWS EvgZUlDa,...,1,1,1463176270,1487132229,0,NaN,NaN,NaN,NaN,gregorian
2,0,1,0,0,1,user7133053338412646401,NaN,drbW XEKAWJ Uuf xI SHCBFLbQB H,bk HPF g bJfbmkXA ELjDgTfXK,xsRHIwCM JQpY d fDPEwoCpuHN EQ,...,1,1,1463259148,1487132092,0,NaN,NaN,NaN,NaN,gregorian
3,0,1,0,0,1,user3543713697010548737,NaN,j jFL wXXlycRoDTOOFkDATM Wn xY,ntXGuKKFnZM DDzIKJ SGcDDAQ,TeE GqMSCATQZ y DSadhGXurEnmVqH,...,1,1,1452399813,1487132086,0,NaN,NaN,NaN,NaN,gregorian
4,0,1,0,0,1,user1626801571545219073,NaN,ELnLGLosOo ZpbuQ p Rltre o EX,BWH tPHVEGvLM FR WAOcwKuJfC,CbR iOB d P ZIvAsUcVGJcHVpWwba,...,1,1,1464780978,1487132339,0,NaN,NaN,NaN,NaN,gregorian

In [8]:
user_df.columns

Index([u'id', u'confirmed', u'deleted', u'suspended', u'mnethostid',
       u'username', u'idnumber', u'firstname', u'lastname', u'email',
       u'emailstop', u'icq', u'skype', u'yahoo', u'aim', u'msn', u'phone1',
       u'phone2', u'institution', u'department', u'address', u'city',
       u'country', u'lang', u'theme', u'timezone', u'firstaccess',
       u'lastaccess', u'lastlogin', u'currentlogin', u'lastip', u'picture',
       u'url', u'description', u'descriptionformat', u'mailformat',
       u'maildigest', u'maildisplay', u'autosubscribe', u'trackforums',
       u'timecreated', u'timemodified', u'trustbitmask', u'lastnamephonetic',
       u'firstnamephonetic', u'middlename', u'alternatename', u'calendartype'],
      dtype='object')

Show what columns have all the same values and should be dropped:

In [10]:
for c in user_df.columns:
    if len(user_df[c].unique()) == 1:
        print c, user_df[c][0]

id 0
confirmed 1
deleted 0
suspended 0
mnethostid 1
idnumber nan
emailstop 0
aim nan
picture 0
descriptionformat 1
trustbitmask 0
calendartype gregorian

In [11]:
users = user_df.drop([c for c in user_df.columns if len(user_df[c].unique()) == 1], axis=1)

In [12]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2170 entries, 0 to 2169
Data columns (total 36 columns):
username             2170 non-null object
firstname            2170 non-null object
lastname             2170 non-null object
email                2170 non-null object
icq                  1 non-null object
skype                26 non-null object
yahoo                5 non-null object
msn                  2 non-null object
phone1               19 non-null object
phone2               23 non-null object
institution          49 non-null object
department           36 non-null object
address              21 non-null object
city                 1861 non-null object
country              2063 non-null object
lang                 2170 non-null object
theme                4 non-null object
timezone             2170 non-null object
firstaccess          2170 non-null int64
lastaccess           2170 non-null int64
lastlogin            2170 non-null int64
currentlogin         2170 non-null int64
lastip               2170 non-null object
url                  74 non-null object
description          243 non-null object
mailformat           2170 non-null int64
maildigest           2170 non-null int64
maildisplay          2170 non-null int64
autosubscribe        2170 non-null int64
trackforums          2170 non-null int64
timecreated          2170 non-null int64
timemodified         2170 non-null int64
lastnamephonetic     21 non-null object
firstnamephonetic    27 non-null object
middlename           8 non-null object
alternatename        12 non-null object
dtypes: int64(11), object(25)
memory usage: 610.4+ KB

In [22]:
users.country.unique()

array(['AU', nan], dtype=object)

In [19]:
users.country.isnull().sum()

107

In [20]:
users.city.isnull().sum()

309

In [24]:
len(users.city.unique())

1860

In [25]:
users.lang.unique()

array(['en_us', 'es', 'en', 'bg', 'it', 'es_mx', 'fr', 'uk', 'ja', 'ru',
       'nl', 'vi', 'pt_br', 'ko', 'de', 'zh_tw', 'pt', 'he', 'lt', 'pl',
       'da', 'no', 'el', 'hr', 'sv', 'ca', 'zh_cn', 'sl', 'ar', 'es_ve',
       'hu', 'sr', 'sr_lt', 'sk', 'hi', 'tr', 'fr_ca', 'is', 'ro', 'id',
       'th', 'ur'], dtype=object)

### Badges

In [26]:
badge_df = pd.read_csv("data/raw/mdl_badge_issued.csv")

In [27]:
badge_df.head()

,username,uniquehash,dateissued,visible
0,user6442803380426375169,dff34e86c5ac6c8ec7650673998a2c5f66a33e53,1470554624,1
1,user6442803380426375169,dff34e86c5ac6c8ec7650673998a2c5f66a33e53,1470554624,1
2,user8540069828419911681,a4f714807acfdb2c8a6367f095ee9179b590e333,1470554624,1
3,user8540069828419911681,a4f714807acfdb2c8a6367f095ee9179b590e333,1470554624,1
4,user2882394166283730945,c9a55d27a003befb7f7da54d2f919435b05504d1,1470554624,1

In [34]:
badge_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1844 entries, 0 to 1843
Data columns (total 4 columns):
username      1844 non-null object
uniquehash    1844 non-null object
dateissued    1844 non-null int64
visible       1844 non-null int64
dtypes: int64(2), object(2)
memory usage: 57.7+ KB

In [31]:
badge_df.groupby('username').count().uniquehash.max()

3

In [33]:
len(badge_df.uniquehash.unique())

1842

## Log

In [5]:
log_df = pd.read_csv("../data/interim/mdl_logstore_standard_log_100000.csv")

/Users/kdmytro/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
log_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99932 entries, 0 to 99931
Data columns (total 21 columns):
username             99932 non-null object
id                   99932 non-null int64
eventname            99932 non-null object
component            99932 non-null object
action               99932 non-null object
target               99932 non-null object
objecttable          35712 non-null object
objectid             35712 non-null float64
crud                 99932 non-null object
edulevel             99932 non-null int64
contextid            99932 non-null int64
contextlevel         99932 non-null int64
contextinstanceid    99932 non-null int64
courseid             99932 non-null int64
anonymous            99932 non-null int64
other                99932 non-null object
timecreated          99932 non-null int64
origin               99932 non-null object
ip                   99932 non-null object
relatedusername      109 non-null object
realusername         19 non-null object
dtypes: float64(1), int64(8), object(12)
memory usage: 16.0+ MB

In [8]:
log_df[log_df.columns[20]]
log_df.columns[20]

'realusername'

In [7]:
log_df.head(3).T

,0,1,2
username,user8540069828419911681,user8540069828419911681,user6442803380426375169
id,25017,25017,37433
eventname,\core\event\course_viewed,\core\event\course_viewed,\core\event\course_viewed
component,core,core,core
action,viewed,viewed,viewed
target,course,course,course
objecttable,NaN,NaN,NaN
objectid,NaN,NaN,NaN
crud,r,r,r
edulevel,2,2,2
contextid,107483,107483,107483
contextlevel,50,50,50
contextinstanceid,5282,5282,5282
courseid,5282,5282,5282
anonymous,0,0,0
other,N;,N;,N;
timecreated,1417771086,1417771086,1417859881
origin,web,web,web
ip,0.0.0.0,0.0.0.0,0.0.0.0
relatedusername,NaN,NaN,NaN
realusername,NaN,NaN,NaN

In [10]:
# Create, Read, Update, Delete
log_df.crud.unique()

array(['r', 'c', 'u', 'd'], dtype=object)

In [14]:
sorted(log_df.eventname.unique())

['\\booktool_exportimscp\\event\\book_exported',
 '\\booktool_print\\event\\book_printed',
 '\\core\\event\\blog_comment_created',
 '\\core\\event\\blog_entries_viewed',
 '\\core\\event\\blog_entry_created',
 '\\core\\event\\blog_entry_deleted',
 '\\core\\event\\calendar_event_created',
 '\\core\\event\\calendar_event_deleted',
 '\\core\\event\\calendar_event_updated',
 '\\core\\event\\course_category_created',
 '\\core\\event\\course_content_deleted',
 '\\core\\event\\course_deleted',
 '\\core\\event\\course_module_completion_updated',
 '\\core\\event\\course_module_created',
 '\\core\\event\\course_module_deleted',
 '\\core\\event\\course_module_updated',
 '\\core\\event\\course_restored',
 '\\core\\event\\course_section_updated',
 '\\core\\event\\course_updated',
 '\\core\\event\\course_viewed',
 '\\core\\event\\message_contact_added',
 '\\core\\event\\message_contact_removed',
 '\\core\\event\\message_sent',
 '\\core\\event\\message_viewed',
 '\\core\\event\\notes_viewed',
 '\\core\\event\\recent_activity_viewed',
 '\\core\\event\\role_assigned',
 '\\core\\event\\role_capabilities_updated',
 '\\core\\event\\role_deleted',
 '\\core\\event\\role_unassigned',
 '\\core\\event\\tag_added',
 '\\core\\event\\tag_created',
 '\\core\\event\\tag_deleted',
 '\\core\\event\\tag_removed',
 '\\core\\event\\tag_updated',
 '\\core\\event\\user_deleted',
 '\\core\\event\\user_enrolment_created',
 '\\core\\event\\user_enrolment_deleted',
 '\\core\\event\\user_graded',
 '\\core\\event\\user_list_viewed',
 '\\core\\event\\user_loggedin',
 '\\core\\event\\user_loggedinas',
 '\\core\\event\\user_loggedout',
 '\\core\\event\\user_login_failed',
 '\\core\\event\\user_password_updated',
 '\\core\\event\\user_profile_viewed',
 '\\core\\event\\user_updated',
 '\\core\\event\\webservice_function_called',
 '\\core\\event\\webservice_token_sent',
 '\\gradereport_grader\\event\\grade_report_viewed',
 '\\gradereport_user\\event\\grade_report_viewed',
 '\\mod_assign\\event\\submission_status_viewed',
 '\\mod_bigbluebuttonbn\\event\\bigbluebuttonbn_activity_viewed',
 '\\mod_bigbluebuttonbn\\event\\bigbluebuttonbn_meeting_created',
 '\\mod_bigbluebuttonbn\\event\\bigbluebuttonbn_meeting_joined',
 '\\mod_bigbluebuttonbn\\event\\bigbluebuttonbn_meeting_left',
 '\\mod_book\\event\\chapter_created',
 '\\mod_book\\event\\chapter_deleted',
 '\\mod_book\\event\\chapter_updated',
 '\\mod_book\\event\\chapter_viewed',
 '\\mod_book\\event\\course_module_viewed',
 '\\mod_chat\\event\\course_module_viewed',
 '\\mod_chat\\event\\message_sent',
 '\\mod_chat\\event\\sessions_viewed',
 '\\mod_choice\\event\\answer_submitted',
 '\\mod_choice\\event\\answer_updated',
 '\\mod_choice\\event\\course_module_instance_list_viewed',
 '\\mod_choice\\event\\course_module_viewed',
 '\\mod_choice\\event\\report_viewed',
 '\\mod_data\\event\\course_module_viewed',
 '\\mod_data\\event\\field_created',
 '\\mod_data\\event\\record_created',
 '\\mod_data\\event\\template_updated',
 '\\mod_data\\event\\template_viewed',
 '\\mod_feedback\\event\\course_module_instance_list_viewed',
 '\\mod_feedback\\event\\course_module_viewed',
 '\\mod_folder\\event\\course_module_viewed',
 '\\mod_folder\\event\\folder_updated',
 '\\mod_forum\\event\\assessable_uploaded',
 '\\mod_forum\\event\\course_module_instance_list_viewed',
 '\\mod_forum\\event\\course_module_viewed',
 '\\mod_forum\\event\\course_searched',
 '\\mod_forum\\event\\discussion_created',
 '\\mod_forum\\event\\discussion_deleted',
 '\\mod_forum\\event\\discussion_moved',
 '\\mod_forum\\event\\discussion_subscription_created',
 '\\mod_forum\\event\\discussion_subscription_deleted',
 '\\mod_forum\\event\\discussion_updated',
 '\\mod_forum\\event\\discussion_viewed',
 '\\mod_forum\\event\\post_created',
 '\\mod_forum\\event\\post_deleted',
 '\\mod_forum\\event\\post_updated',
 '\\mod_forum\\event\\user_report_viewed',
 '\\mod_glossary\\event\\course_module_instance_list_viewed',
 '\\mod_glossary\\event\\course_module_viewed',
 '\\mod_glossary\\event\\entry_created',
 '\\mod_glossary\\event\\entry_deleted',
 '\\mod_glossary\\event\\entry_updated',
 '\\mod_glossary\\event\\entry_viewed',
 '\\mod_lesson\\event\\course_module_viewed',
 '\\mod_lesson\\event\\lesson_ended',
 '\\mod_lesson\\event\\lesson_started',
 '\\mod_lti\\event\\course_module_viewed',
 '\\mod_page\\event\\course_module_viewed',
 '\\mod_quiz\\event\\attempt_deleted',
 '\\mod_quiz\\event\\attempt_started',
 '\\mod_quiz\\event\\attempt_submitted',
 '\\mod_quiz\\event\\attempt_viewed',
 '\\mod_quiz\\event\\course_module_viewed',
 '\\mod_quiz\\event\\edit_page_viewed',
 '\\mod_quiz\\event\\report_viewed',
 '\\mod_recordingsbn\\event\\recordingsbn_recording_published',
 '\\mod_recordingsbn\\event\\recordingsbn_resource_page_viewed',
 '\\mod_resource\\event\\course_module_viewed',
 '\\mod_survey\\event\\course_module_viewed',
 '\\mod_survey\\event\\report_viewed',
 '\\mod_survey\\event\\response_submitted',
 '\\mod_url\\event\\course_module_viewed',
 '\\mod_wiki\\event\\comments_viewed',
 '\\mod_wiki\\event\\course_module_viewed',
 '\\mod_wiki\\event\\page_created',
 '\\mod_wiki\\event\\page_deleted',
 '\\mod_wiki\\event\\page_diff_viewed',
 '\\mod_wiki\\event\\page_history_viewed',
 '\\mod_wiki\\event\\page_locks_deleted',
 '\\mod_wiki\\event\\page_map_viewed',
 '\\mod_wiki\\event\\page_updated',
 '\\mod_wiki\\event\\page_version_deleted',
 '\\mod_wiki\\event\\page_viewed',
 '\\mod_workshop\\event\\course_module_viewed',
 '\\mod_workshop\\event\\phase_switched',
 '\\report_log\\event\\report_viewed',
 '\\report_loglive\\event\\report_viewed',
 '\\report_outline\\event\\activity_report_viewed',
 '\\report_stats\\event\\report_viewed',
 '\\tool_langimport\\event\\langpack_imported',
 '\\tool_langimport\\event\\langpack_removed',
 '\\tool_langimport\\event\\langpack_updated']

In [36]:
log_counts = log_df.groupby('eventname', sort=False).count()['id'].sort_values(ascending=False)
log_counts

eventname
\core\event\message_sent                                   50115
\core\event\course_viewed                                   9358
\mod_forum\event\discussion_viewed                          9096
\core\event\message_viewed                                  7778
\mod_forum\event\course_module_viewed                       5497
\core\event\webservice_function_called                      3975
\mod_forum\event\assessable_uploaded                        1625
\core\event\user_profile_viewed                             1316
\mod_book\event\chapter_viewed                              1270
\mod_forum\event\post_created                               1252
\core\event\user_loggedin                                    961
\core\event\user_list_viewed                                 826
\mod_page\event\course_module_viewed                         771
\mod_wiki\event\page_viewed                                  452
\mod_book\event\course_module_viewed                         362
\mod_forum\event\post_updated                                302
\mod_forum\event\discussion_subscription_created             277
\core\event\course_module_updated                            270
\core\event\user_loggedout                                   228
\core\event\blog_entries_viewed                              218
\mod_choice\event\course_module_viewed                       195
\core\event\course_updated                                   194
\mod_folder\event\course_module_viewed                       188
\mod_wiki\event\course_module_viewed                         177
\mod_forum\event\user_report_viewed                          149
\mod_chat\event\sessions_viewed                              149
\core\event\course_module_completion_updated                 143
\mod_book\event\chapter_updated                              129
\mod_wiki\event\page_map_viewed                              127
\mod_quiz\event\course_module_viewed                         120
                                                           ...
\core\event\tag_created                                        2
\core\event\role_deleted                                       2
\core\event\notes_viewed                                       2
\mod_chat\event\message_sent                                   2
\mod_choice\event\course_module_instance_list_viewed           2
\core\event\course_deleted                                     2
\mod_workshop\event\phase_switched                             2
\mod_assign\event\submission_status_viewed                     2
\core\event\course_category_created                            2
\mod_data\event\template_viewed                                2
\mod_data\event\record_created                                 2
\booktool_exportimscp\event\book_exported                      2
\core\event\course_restored                                    2
\mod_lesson\event\lesson_ended                                 2
\core\event\role_assigned                                      2
\core\event\course_content_deleted                             2
\mod_bigbluebuttonbn\event\bigbluebuttonbn_meeting_left        1
\mod_quiz\event\attempt_submitted                              1
\core\event\tag_deleted                                        1
\mod_quiz\event\attempt_viewed                                 1
\mod_choice\event\answer_updated                               1
\report_loglive\event\report_viewed                            1
\mod_lti\event\course_module_viewed                            1
\mod_data\event\template_updated                               1
\core\event\blog_entry_created                                 1
\mod_glossary\event\entry_updated                              1
\mod_feedback\event\course_module_instance_list_viewed         1
\core\event\recent_activity_viewed                             1
\gradereport_user\event\grade_report_viewed                    1
\mod_glossary\event\course_module_instance_list_viewed         1
Name: id, dtype: int64

In [44]:
import numpy as np
rare_events = log_counts[log_counts < 3].index
log_df.where('eventname' in rare_events)

ValueError: where requires an ndarray like object for its condition

In [38]:
course_modules_df = pd.read_csv("../data/raw/mdl_course_modules.csv")

In [39]:
course_modules_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 21 columns):
name                         60 non-null object
id                           60 non-null int64
course                       60 non-null int64
module                       60 non-null int64
instance                     60 non-null int64
section                      60 non-null int64
idnumber                     0 non-null float64
added                        60 non-null int64
score                        60 non-null int64
indent                       60 non-null int64
visible                      60 non-null int64
visibleold                   60 non-null int64
groupmode                    60 non-null int64
groupingid                   60 non-null int64
completion                   60 non-null int64
completiongradeitemnumber    4 non-null float64
completionview               60 non-null int64
completionexpected           60 non-null int64
showdescription              60 non-null int64
availability                 7 non-null object
deletioninprogress           60 non-null int64
dtypes: float64(2), int64(17), object(2)
memory usage: 9.9+ KB

In [40]:
course_modules_df.head(3).T

                                    0           1           2
name                            forum      survey    feedback
id                              54984       55004       54995
course                          10464       10464       10464
module                              9          19           7
instance                        13387         662        1007
section                         58964       58966       58965
idnumber                          NaN         NaN         NaN
added                      1372670270  1378189004  1372678410
score                               0           0           0
indent                              0           0           0
visible                             1           1           1
visibleold                          1           1           1
groupmode                           0           0           0
groupingid                          0           0           0
completion                          1           1           2
completiongradeitemnumber         NaN         NaN         NaN
completionview                      0           0           0
completionexpected                  0           0           0
showdescription                     0           0           0
availability                      NaN         NaN         NaN
deletioninprogress                  0           0           0

In [50]:
course_modules_df[course_modules_df.section == 58964]

,name,id,course,module,instance,section,idnumber,added,score,indent,...,visibleold,groupmode,groupingid,completion,completiongradeitemnumber,completionview,completionexpected,showdescription,availability,deletioninprogress
0,forum,54984,10464,9,13387,58964,NaN,1372670270,0,0,...,1,0,0,1,NaN,0,0,0,NaN,0
12,page,54985,10464,15,4211,58964,NaN,1377683443,0,0,...,1,0,0,1,NaN,0,0,0,NaN,0
47,page,55043,10464,15,4226,58964,NaN,1457605162,0,0,...,1,0,0,1,NaN,0,0,0,NaN,0
52,label,55329,10464,12,5478,58964,NaN,1470636237,0,0,...,1,0,0,0,NaN,0,0,0,NaN,0
54,label,54987,10464,12,5447,58964,NaN,1420804201,0,0,...,1,0,0,0,NaN,0,0,0,NaN,0
56,page,54986,10464,15,4212,58964,NaN,1377683443,0,0,...,1,0,0,1,NaN,0,0,0,NaN,0

In [41]:
grades_history_df = pd.read_csv("../data/raw/mdl_grade_grades_history.csv")

In [42]:
grades_history_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70037 entries, 0 to 70036
Data columns (total 24 columns):
username             70037 non-null object
id                   70037 non-null int64
action               70037 non-null int64
oldid                70037 non-null int64
source               34311 non-null object
timemodified         70037 non-null int64
itemid               70037 non-null int64
rawgrade             8720 non-null float64
rawgrademax          70037 non-null float64
rawgrademin          70037 non-null float64
rawscaleid           943 non-null float64
usermodified         8755 non-null float64
finalgrade           22054 non-null float64
hidden               70037 non-null int64
locked               70037 non-null int64
locktime             70037 non-null int64
exported             70037 non-null int64
overridden           70037 non-null int64
excluded             70037 non-null int64
feedback             34 non-null object
feedbackformat       70037 non-null int64
information          0 non-null float64
informationformat    70037 non-null int64
loggedusername       69957 non-null object
dtypes: float64(7), int64(13), object(4)
memory usage: 12.8+ MB

In [43]:
grades_history_df[~grades_history_df.feedback.isnull()]

,username,id,action,oldid,source,timemodified,itemid,rawgrade,rawgrademax,rawgrademin,...,locked,locktime,exported,overridden,excluded,feedback,feedbackformat,information,informationformat,loggedusername
962,user8023781421904560129,284988,2,112285,NaN,1471960353,20576,100.0,100.0,0.0,...,0,0,0,0,0,MVfk vsH UeAlQiWM,1,NaN,0,user8540069828419911681
963,user8023781421904560129,270840,2,112285,NaN,1471958904,20576,100.0,100.0,0.0,...,0,0,0,0,0,RSKDHaqO YPY AYQW,1,NaN,0,user8540069828419911681
968,user8023781421904560129,247358,2,112285,mod/assign,1471845824,20576,100.0,100.0,0.0,...,0,0,0,0,0,gRQLjV J FxW Mi,1,NaN,0,user6442803380426375169
1975,user1665969594520567809,301749,2,112780,mod/assign,1472377257,20576,100.0,100.0,0.0,...,0,0,0,0,0,StSLhbyi dvbZgTL,1,NaN,0,user6442803380426375169
3750,user1538973497546506241,302554,2,119053,mod/assign,1472457317,20576,100.0,100.0,0.0,...,0,0,0,0,0,JA GwVnHBV,1,NaN,0,user6442803380426375169
4443,user1406505393194008577,299047,2,111833,mod/assign,1472066005,20576,100.0,100.0,0.0,...,0,0,0,0,0,XrkEzudOu fvnadMt,1,NaN,0,user6442803380426375169
6888,user2000452477777870849,304635,2,128248,mod/assign,1472622623,20576,100.0,100.0,0.0,...,0,0,0,0,0,VLqlxj H N,1,NaN,0,user6442803380426375169
17943,user5350080554052091905,302560,2,131082,mod/assign,1472457318,20576,100.0,100.0,0.0,...,0,0,0,0,0,zCgHlqeRIV,1,NaN,0,user6442803380426375169
18203,user4791183426260566017,302559,2,119113,mod/assign,1472457317,20576,100.0,100.0,0.0,...,0,0,0,0,0,KuqLMG ZHM,1,NaN,0,user6442803380426375169
23450,user7542936550099648513,311671,2,125689,mod/assign,1472667316,20576,100.0,100.0,0.0,...,0,0,0,0,0,nY f mSrvW,1,NaN,0,user6442803380426375169
25740,user7672648505218826241,299048,2,118554,mod/assign,1472066127,20576,100.0,100.0,0.0,...,0,0,0,0,0,e NDjX AAAUq DBoG,1,NaN,0,user6442803380426375169
26099,user1283475891791331329,300085,2,114525,mod/assign,1472150845,20576,100.0,100.0,0.0,...,0,0,0,0,0,ooN nwpZBLfAxyUYK,1,NaN,0,user6442803380426375169
26783,user6890768104326955009,301142,2,111063,mod/assign,1472280415,20576,100.0,100.0,0.0,...,0,0,0,0,0,nx hLTxyCifPleJ,1,NaN,0,user6442803380426375169
28283,user6740062254575648769,302557,2,115699,mod/assign,1472457317,20576,100.0,100.0,0.0,...,0,0,0,0,0,rqkHgvKecj,1,NaN,0,user6442803380426375169
32467,user2200250830219640833,301352,2,112750,mod/assign,1472310838,20576,100.0,100.0,0.0,...,0,0,0,0,0,EID nIumPc YtzBn,1,NaN,0,user6442803380426375169
33551,user51854703532703745,300692,2,123620,mod/assign,1472228362,20576,100.0,100.0,0.0,...,0,0,0,0,0,qQVtqlJYrXgTO jOp,1,NaN,0,user6442803380426375169
33952,user7776217578522804225,296501,2,111593,mod/assign,1471964081,20576,100.0,100.0,0.0,...,0,0,0,0,0,vPmJgRQB nrDD SCa,1,NaN,0,user6442803380426375169
35176,user1517687459238903809,302558,2,110249,mod/assign,1472457317,20576,100.0,100.0,0.0,...,0,0,0,0,0,L ZWVLkMqz,1,NaN,0,user6442803380426375169
40787,user7163092528659431425,313350,2,125321,mod/assign,1472907935,20576,100.0,100.0,0.0,...,0,0,0,0,0,eUp z F A,1,NaN,0,user6442803380426375169
46406,user2812961982674632705,303128,2,108005,mod/assign,1472484482,20576,100.0,100.0,0.0,...,0,0,0,0,0,umFpwG Llf,1,NaN,0,user6442803380426375169
47279,user1111099440950673409,313178,2,109274,mod/assign,1472848571,20576,100.0,100.0,0.0,...,0,0,0,0,0,QoIPtaaXxq,1,NaN,0,user6442803380426375169
47374,user113100542036672513,297814,2,110279,mod/assign,1472021640,20576,100.0,100.0,0.0,...,0,0,0,0,0,M FKCGtZHbJkZ YL,1,NaN,0,user6442803380426375169
48421,user5394195829596618753,299055,2,128340,mod/assign,1472066402,20576,100.0,100.0,0.0,...,0,0,0,0,0,OMxIXBknbKag HQpE,1,NaN,0,user6442803380426375169
52391,user8186571780618452993,249474,2,108641,mod/assign,1471951374,20576,100.0,100.0,0.0,...,0,0,0,0,0,jRsPcDGCUKfHaGxe,1,NaN,0,user6442803380426375169
52392,user8186571780618452993,270835,2,108641,NaN,1471958904,20576,100.0,100.0,0.0,...,0,0,0,0,0,IS QwPmTBYp FdLjr,1,NaN,0,user8540069828419911681
52393,user8186571780618452993,284983,2,108641,NaN,1471960352,20576,100.0,100.0,0.0,...,0,0,0,0,0,Eb YUCbCjWoq wTTt,1,NaN,0,user8540069828419911681
56817,user9081585137665179649,298465,2,108611,mod/assign,1472042845,20576,100.0,100.0,0.0,...,0,0,0,0,0,FmHgBdiXLnXVTwjHE,1,NaN,0,user6442803380426375169
57608,user2943964197509136385,299053,2,107211,mod/assign,1472066270,20576,100.0,100.0,0.0,...,0,0,0,0,0,alrn WrbKed ecWVT,1,NaN,0,user6442803380426375169
60136,user4630807835599437825,311669,2,132284,mod/assign,1472667316,20576,100.0,100.0,0.0,...,0,0,0,0,0,L wUwi Y,1,NaN,0,user6442803380426375169
61094,user2836743929557155841,303793,2,108232,mod/assign,1472540111,20576,100.0,100.0,0.0,...,0,0,0,0,0,qhTJHzQj f,1,NaN,0,user6442803380426375169
64656,user3760051457408106497,300695,2,122577,mod/assign,1472228492,20576,100.0,100.0,0.0,...,0,0,0,0,0,BErCkvd XxbWsCDB,1,NaN,0,user6442803380426375169
67436,user904572597037957121,299543,2,130303,mod/assign,1472104583,20576,100.0,100.0,0.0,...,0,0,0,0,0,YO Tm AAvc FAZKEWyMuIzFbTiRamzCqPCzirhNiqmSP C...,1,NaN,0,user6442803380426375169
67437,user904572597037957121,299541,2,130303,mod/assign,1472104572,20576,100.0,100.0,0.0,...,0,0,0,0,0,pkgRuNhGsVGzRccdhNDMRP kOtcJgMCkCD Oeaf WiBfAj...,1,NaN,0,user6442803380426375169
67438,user904572597037957121,302556,2,130303,mod/assign,1472457317,20576,100.0,100.0,0.0,...,0,0,0,0,0,A sqKoUMbD k pst Ssn Z IbRHB nNuicnGczpMwqRq...,1,NaN,0,user6442803380426375169